title: Thomas Tran
description: Welcome to my website!
theme: jekyll-theme-minimal

# Asset configuration
logo: /assets/images/logo.png

# Skills and interests sections
skills:
  - name: VS Code
    icon: fa-brands fa-vs
    color: "#007ACC"
  - name: Python
    icon: fa-brands fa-python
    color: "#3776AB"
  - name: GitHub
    icon: fa-brands fa-github
    color: "#181717"

interests:
  - name: Gaming
    icon: fa-gamepad
  - name: Photography
    icon: fa-camera
  - name: Music
    icon: fa-music
  - name: Reading
    icon: fa-book

# Add Font Awesome via CDN
font_awesome_kit: # your kit code if you have one, or leave empty to use the free CDN

# Your social media and contact info
social_links:
  github: tommytt427
  linkedin: ttrann3
  email: ttrann@umich.edu
# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
