title: Thomas Tran
description: Welcome to my website!
theme: jekyll-theme-minimal

# Asset configuration
logo: /assets/images/logo.png

# Add Font Awesome via CDN
font_awesome_kit: # your kit code if you have one, or leave empty to use the free CDN

# Your social media and contact info
social_links:
  github: tommytt427
  linkedin: ttrann3
  email: ttrann@umich.edu
# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project-guide"
