title: Thomas Tran
description: Welcome to my website!
theme: jekyll-theme-minimal

# Asset configuration
logo: /assets/images/logo.png

# Add Font Awesome via CDN
font_awesome_kit: # your kit code if you have one, or leave empty to use the free CDN

# Your social media and contact info
social_links:
  github: https://github.com/tommytt427
  linkedin: https://www.linkedin.com/in/ttrann3/
  email: ttrann@umich.edu
