title: Thomas Tran
description: Welcome to my website!
theme: jekyll-theme-minimal

# Asset configuration
logo: /assets/images/logo.png

# Social media and contact links
github_username: tommytt427
linkedin_url: https://www.linkedin.com/in/ttrann3/
email: ttrann@umich.edu

# Additional settings
show_downloads: false
google_analytics: # your analytics ID here

# Collections (if you want to organize content)
collections:
  projects:
    output: true
    permalink: /projects/:path/
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
