title: Your Name
description: A short description of your site
theme: jekyll-theme-minimal
show_downloads: false
google_analytics: # your analytics ID (optional)

# You can customize your theme's look further
# The available options depend on the theme you choose
